import { GAME_DISTRICTS } from './districts.js';
const control=(id,label,title)=>'<button id="'+id+'" title="'+title+'" aria-label="'+title+'">'+label+'</button>';
export function createGameUI(){const root=document.createElement('div');root.id='game-ui';root.innerHTML=[
'<div id="game-start" class="game-start"><div class="game-intro"><div class="game-kicker">A BROWSER WORLD · FIVE PLAYABLE DISTRICTS</div><h1>VICE<br><span>HORIZON</span></h1><p>Run the coast. Chase the tide.<br>Make the city your own.</p><div class="start-actions"><button id="begin-game" class="primary">ENTER LEONIDA <span>→</span></button><a href="?studio=1">Explore the scene studies</a></div><div class="start-foot">DRIVING · BOATING · RACES · PURSUITS<br>WASD to move · E to enter / exit · Shift for boost<br>Single-player · progress saved on this browser</div></div><div class="intro-aside"><span>01 — 05</span><b>FIVE DISTRICTS.<br>ONE LONG NIGHT.</b><small>Original browser game inspired by your reference scenes.<br>Visuals and characters remain under development.</small></div></div>',
'<div id="game-hud" class="game-hud hidden"><header class="game-top"><div class="game-brand">VH <span id="district-name"></span></div><div class="game-account"><span id="cash"></span><span id="xp"></span><span id="heat" aria-label="Pursuit heat"></span></div></header>',
'<div id="mission-card" class="mission-card"><span id="mission-kind"></span><h2 id="mission-title"></h2><p id="mission-detail"></p><div class="mission-bottom"><b id="mission-counter"></b><span id="mission-time"></span></div></div>',
'<div class="game-map"><canvas id="mini-map" width="256" height="256" aria-label="District map with player, objectives and patrols"></canvas><span id="map-caption"></span></div>',
'<div class="speedometer"><span id="vehicle-label">SUNRISE GT</span><div><b id="speed">0</b><small>KM/H</small></div><span id="interaction-hint">E — exit vehicle</span><div class="meters"><label>INTEGRITY <progress id="integrity" max="100" value="100"></progress></label><label>NITRO <progress id="nitro" max="100" value="100"></progress></label></div></div>',
'<nav class="game-actions">'+control('open-map','MAP','Open districts and missions (M)')+control('open-garage','GARAGE','Open garage (G)')+control('game-camera','CAMERA','Change driving camera (C)')+control('game-sound','SOUND ON','Toggle sound')+control('game-pause','Ⅱ','Pause game (Escape)')+'</nav>',
'<div class="game-help">WASD / arrows · E enter / exit · Shift boost · Space brake / jump · R recover · Q horn</div><div id="game-toast" class="game-toast hidden" role="status"></div><div id="game-banner" class="game-banner hidden" role="status"></div>',
'<div class="touch-drive"><button data-drive="left" aria-label="Steer left">←</button><button data-drive="right" aria-label="Steer right">→</button><button data-drive="reverse" aria-label="Reverse or brake">↓</button><button data-drive="forward" aria-label="Accelerate">↑</button><button data-drive="boost" aria-label="Use nitro">BOOST</button><button id="touch-interact" aria-label="Enter or exit vehicle">E</button></div></div>',
'<div id="game-menu" class="game-menu hidden" role="dialog" aria-modal="true" aria-labelledby="menu-title"><div class="menu-shell"><header><div><span class="game-kicker">VICE HORIZON</span><h2 id="menu-title">THE CITY IS YOURS</h2></div><button id="close-menu" aria-label="Resume game">RESUME ×</button></header><div id="menu-content"></div><footer><button id="recover-game">RECOVER VEHICLE</button><button id="photo-game">PHOTO / SCENE STUDIO</button><label>RENDER <select id="game-quality" aria-label="Game render quality"><option value="high">High</option><option value="balanced" selected>Balanced</option><option value="draft">Draft</option></select></label><label><input id="music-enabled" type="checkbox" checked> ORIGINAL SYNTH RADIO</label></footer></div></div>'
].join('');document.body.append(root);return root;}
export function districtCards(active){return '<div class="district-cards">'+GAME_DISTRICTS.map((d,i)=>'<button data-travel="'+i+'" class="district-card '+(active===i?'selected':'')+'" style="--district-color:'+d.color+'"><span>0'+(i+1)+'</span><b>'+d.name+'</b><small>'+d.tag+'</small></button>').join('')+'</div>';}
